version: "3.8"

services:
  docker-summary:
    image: nirgf/docker-summary:latest
    container_name: docker-summary
    ports:
      - "8090:8090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app:/app  # persist local
    environment:
      - TZ=Asia/Jerusalem
    restart: unless-stopped
